<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Authors>Hubert "uZer" Szymik</Authors>
    <Company>uZer</Company>
    <ApplicationIcon>ico.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="IMG\Logo.png" />
    <None Remove="IMG\Password.ttf" />
    <None Remove="Logo.png" />
    <None Remove="MaxWindow.png" />
    <None Remove="MinWindow.png" />
    <None Remove="X.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="IMG\Logo.png" />
    <Resource Include="IMG\Password.ttf" />
    <Resource Include="IMG\X.png" />
    <Resource Include="IMG\MaxWindow.png" />
    <Resource Include="IMG\MinWindow.png" />
    <Resource Include="Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Apps\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ForesterUpdater\ForesterUpdater.deps.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ForesterUpdater\ForesterUpdater.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ForesterUpdater\ForesterUpdater.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ForesterUpdater\ForesterUpdater.pdb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ForesterUpdater\ForesterUpdater.runtimeconfig.dev.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ForesterUpdater\ForesterUpdater.runtimeconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ForesterUpdater\Newtonsoft.Json.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ForesterUpdater\ref\ForesterUpdater.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
