<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\forester-logo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <None Remove=".gitignore" />
    <None Remove="Assets\settings.png" />
  </ItemGroup>
  <ItemGroup>
	  <AvaloniaXaml Include="Views\Style\Login.axaml">
		  <Generator>MSBuild:Compile</Generator>
	  </AvaloniaXaml>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\forester-logo.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.10" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.10" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="0.10.10" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.10.10" />
    <PackageReference Include="RestSharp" Version="107.3.0" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaXaml Update="Views\Style\App.axaml">
      <Generator>MSBuild:Compile</Generator>
    </AvaloniaXaml>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\App\Developer\BasicInfoView.axaml.cs">
      <DependentUpon>BasicInfoView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\App\StoreView.axaml.cs">
      <DependentUpon>StoreView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\App\Store\AppStoreView.axaml.cs">
      <DependentUpon>AppStoreView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\LoginPanelView.axaml.cs">
      <DependentUpon>LoginPanelView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\AppPanelView.axaml.cs">
      <DependentUpon>AppPanelView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Popup\Library\DownloadSettingsView.axaml.cs">
      <DependentUpon>DownloadSettingsView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Popup\SettingsPages\InfoView.axaml.cs">
      <DependentUpon>InfoView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Popup\SettingsPages\ThemeView.axaml.cs">
      <DependentUpon>ThemeView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Popup\SettingsPages\UserProfileView.axaml.cs">
      <DependentUpon>UserProfileView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Popup\SettingsView.axaml.cs">
      <DependentUpon>SettingsView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\TestView.axaml.cs">
      <DependentUpon>TestView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="dataConfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libraryConfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ProjectExtensions><VisualStudio><UserProperties dataconfig_1json__JsonSchema="https://beaujs.com/schema.json" /></VisualStudio></ProjectExtensions>
</Project>
