<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <None Remove=".gitignore" />
  </ItemGroup>
  <ItemGroup>
	  <AvaloniaXaml Include="Views\Style\Login.axaml">
		  <Generator>MSBuild:Compile</Generator>
	  </AvaloniaXaml>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.10" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.10" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="0.10.10" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="0.10.10" />
    <PackageReference Include="RestSharp" Version="107.3.0" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaXaml Update="Views\Style\App.axaml">
      <Generator>MSBuild:Compile</Generator>
    </AvaloniaXaml>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\App\Developer\BasicInfoView.axaml.cs">
      <DependentUpon>BasicInfoView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\LoginPanelView.axaml.cs">
      <DependentUpon>LoginPanelView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\AppPanelView.axaml.cs">
      <DependentUpon>AppPanelView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\TestView.axaml.cs">
      <DependentUpon>TestView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ProjectExtensions><VisualStudio><UserProperties config_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>
</Project>
